GET http://localhost:3000/users
GET http://localhost:3000/users/12345
GET http://localhost:3000/users/aaa
GET http://localhost:3000/users/12345/111
GET http://localhost:3000/users/12345?limit=10&offset=20
GET http://localhost:3000/users/12345/222?limit=10&offset=20